import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import ScrollProgress from "@/components/ui/scroll-progress";
import Nav from "@/components/ui/navbar/Nav";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system">
        <body className={`antialiased`}>
          <Suspense>
            <Nav />
            <ScrollProgress />
            {children}
            <Footer />
          </Suspense>
        </body>
      </ThemeProvider>
    </html>
  );
}
